### ISSUE TITLE
Installed extension(on-prem) is not showing up in task window

### ISSUE THREAD

**Issue by vinimehta** [XpiritBV/Xpirit-Vsts-Release-Settings#4]
Hello, 

I have installed your extension, but when I went back to my task window to check if I can add the task in my build step. However it did not show up. We ran a fiddler trace and it came back with the image attached to this help request. Is there a reason this feature is disabled? could this be the possible issue? 
![extension error](https://cloud.githubusercontent.com/assets/24412504/21732217/79736520-d426-11e6-930c-18e42a818912.PNG)

**Comment by pascalnaber** [comment]
Looks like you are using the task for Azure Automation. Please add the Issue there: https://github.com/XpiritBV/Xpirit.Vsts.Release.RmAutomation
